<a href="https://colab.research.google.com/github/AadityaAdh/tf_variables/blob/main/tf_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

#tf.constant:

Constants are immutable tensors, meaning their values cannot be changed after initialization.
They are used for storing values that remain constant throughout the execution of a program.
Constants are often used for model hyperparameters or fixed values that do not need to be updated during training.

#tf.Variable:
Variables, on the other hand, are mutable tensors that can be modified during the execution of a program.
They are commonly used to represent trainable parameters in machine learning models, such as weights and biases.
Variables are typically used for values that need to be updated and adjusted during the training process.

variabable lai train garda change huna na dini banauna ni milxa tesko trainable vanni attribute lai none garae ra

#tf.variable
    tf.Variable(
      initial_value=None,
      trainable=None,
      validate_shape=True,
      caching_device=None,
      name=None,
      variable_def=None,
      dtype=None,
      import_scope=None,
      constraint=None,
      synchronization=tf.VariableSynchronization.AUTO,
      aggregation=tf.compat.v1.VariableAggregation.NONE,
      shape=None,
      experimental_enable_variable_lifting=True
    )

tei initial value vanya n dimensional array haru
trainable vanya train garda yesko value change garauni ko nai

In [ ]:
x=tf.constant([1,2,3,4])
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x+1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

#yaa ta constant ma jodi ra xa how?

constant are immutable

constant value ma jodna milxa ghatauna milxa aaru j man lagyo tyo garna milxa

tara constant ko value change garna mildaina vanya ho

tyo x ko value jailae pani tei nai hunxa vanya ho aani x ma jodna ghatauna j garna ni mili halxa

#variables are mutable
vanya tyo variables vitra vako value nai pani change garna milxa

by using assign

    variable.assign(your new values)
    

In [ ]:
v = tf.Variable(1.)
v.assign(2.)



<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [ ]:
#tyo value ma certain value jode ra result tya rakhna ni milxa

v = tf.Variable(1.)


v.assign_add(0.5)

#1+0.5=1.5


<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.5>

#constant to variables

    tf.variables(your tf.constant)

In [ ]:
j=tf.constant(1)
j

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.Variable(j)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

#yesto variables haru weight,bias haru ko lagi useful hunxa as tyo values haru change gari ranu parxa